-- Seed CMS permissions into the permission table
INSERT INTO permission (name, description, path, action, is_deleted, created_at, updated_at)
VALUES
    ('View Categories', 'View product categories', '/api/categories', 'GET', false, NOW(), NOW()),
    ('Create Category', 'Create product categories', '/api/categories', 'POST', false, NOW(), NOW()),
    ('Update Category', 'Update product categories', '/api/categories/:id', 'PUT', false, NOW(), NOW()),
    ('Delete Category', 'Delete product categories', '/api/categories/:id', 'DELETE', false, NOW(), NOW()),
    ('View Buildings', 'View buildings', '/api/buildings', 'GET', false, NOW(), NOW()),
    ('Create Building', 'Create buildings', '/api/buildings', 'POST', false, NOW(), NOW()),
    ('Update Building', 'Update buildings', '/api/buildings/:id', 'PUT', false, NOW(), NOW()),
    ('Delete Building', 'Delete buildings', '/api/buildings/:id', 'DELETE', false, NOW(), NOW()),
    ('View Apartments', 'View apartments', '/api/apartments', 'GET', false, NOW(), NOW()),
    ('Create Apartment', 'Create apartments', '/api/apartments', 'POST', false, NOW(), NOW()),
    ('Update Apartment', 'Update apartments', '/api/apartments/:id', 'PUT', false, NOW(), NOW()),
    ('Delete Apartment', 'Delete apartments', '/api/apartments/:id', 'DELETE', false, NOW(), NOW()),
    ('View Products', 'View products', '/api/products', 'GET', false, NOW(), NOW()),
    ('Create Product', 'Create products', '/api/products', 'POST', false, NOW(), NOW()),
    ('Update Product', 'Update products', '/api/products/:id', 'PUT', false, NOW(), NOW()),
    ('Delete Product', 'Delete products', '/api/products/:id', 'DELETE', false, NOW(), NOW()),
    ('View Customers', 'View customers', '/api/customers', 'GET', false, NOW(), NOW()),
    ('Create Customer', 'Create customers', '/api/customers', 'POST', false, NOW(), NOW()),
    ('Update Customer', 'Update customers', '/api/customers/:id', 'PUT', false, NOW(), NOW()),
    ('Delete Customer', 'Delete customers', '/api/customers/:id', 'DELETE', false, NOW(), NOW()),
    ('View Orders', 'View orders', '/api/orders', 'GET', false, NOW(), NOW()),
    ('Create Order', 'Create orders', '/api/orders', 'POST', false, NOW(), NOW()),
    ('Update Order', 'Update orders', '/api/orders/:id', 'PUT', false, NOW(), NOW()),
    ('Delete Order', 'Delete orders', '/api/orders/:id', 'DELETE', false, NOW(), NOW()),
    ('Manage Order Status', 'Update order status', '/api/orders/:id/status', 'PATCH', false, NOW(), NOW()),
    ('View Analytics', 'View analytics dashboard', '/api/analytics', 'GET', false, NOW(), NOW()),
    ('Manage Users', 'Manage SSO users', '/v1/account', '*', false, NOW(), NOW()),
    ('Manage Roles', 'Manage SSO roles', '/v1/role', '*', false, NOW(), NOW()),
    ('Manage Permissions', 'Manage permissions', '/v1/permission', '*', false, NOW(), NOW()),
    ('Manage Policies', 'Manage Casbin policies', '/v1/policy', '*', false, NOW(), NOW())
ON CONFLICT DO NOTHING;
